name: Deploy README to Master Node

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.MASTER_NODE_IP }} >> ~/.ssh/known_hosts

      - name: Copy README.md to Master Node
        run: |
          scp README.md root@${{ secrets.MASTER_NODE_IP }}:/root/testing/
          ls /root/testing/
