name: Workflow with multiple jobs

on:
    push

jobs:
    job_No1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install cowsay 
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay
          run: cowsay -f cow "Run for cover, I am Rozi's COW....MOOO" >> dragon.txt

        - name: Uploading dragon.txt
          uses: actions/upload-artifact@v4
          with:
            name: my-artifact
            path: dragon.txt

    job_No2:
        needs: job_No1
        runs-on: ubuntu-latest
        steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: my-artifact

        - name: If file exists
          run: grep -i "dragon" dragon.txt

        - name: Print result
          run: cat dragon.txt
