name: ASCII Artwork

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install cowsay 
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: If file exists
          run: grep -i "dragon" dragon.txt

        - name: Print result
          run: cat dragon.txt

        - name: Check files
          run: ls -ltra

