name: Scheduled
on: 
  schedule:
    - cron: "*/5 * * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: docker build
      run: echo docker build -t ${{ vars.REGISTRY }}/${{ vars.USERNAME }}/${{ vars.IMAGE }}:latest

    - name: docker login
      run: echo docker login --username=${{ vars.USERNAME }} --password=${{ secrets.PASS }}
    
    - name: docker publish
      run: echo docker push ${{ vars.REGISTRY }}/${{ vars.USERNAME }}/${{ vars.IMAGE }}:latest

  deploy: 
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: docker run
      run: echo docker run -d -p 8080:80 ${{ vars.REGISTRY }}/${{ vars.USERNAME }}/${{ vars.IMAGE }}:latest